# Generated by Django 5.1.1 on 2024-09-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegHumanos',
            new_name='Humanos',
        ),
    ]
